Update labauto

diff --git a/labauto b/labauto
--- a/labauto
+++ b/labauto
@@ -26,15 +26,15 @@ if [ "$EL" != "el7" ]; then
 fi
 
 ### Install ansible
-if [ ! -x /bin/ansible ]; then
-	yum install ansible git -y &>/dev/null
-fi
+# if [ ! -x /bin/ansible ]; then
+# 	yum install ansible git -y &>/dev/null
+# fi
 
 ### Run Playbook
-if [ ! -x /bin/ansible-playbook ]; then
-	error "Unable to find ansible-playbook command .. Seems ansible installation didn't went will. Try to install and try again"
-	exit 1
-fi
+# if [ ! -x /bin/ansible-playbook ]; then
+# 	error "Unable to find ansible-playbook command .. Seems ansible installation didn't went will. Try to install and try again"
+# 	exit 1
+# fi
 
 cd /tmp
 rm -rf labautomation
