ss

diff --git a/tools/roboshop-issue-tracker/functions b/tools/roboshop-issue-tracker/functions
--- a/tools/roboshop-issue-tracker/functions
+++ b/tools/roboshop-issue-tracker/functions
@@ -6,6 +6,10 @@ CASE() {
       echo -e "\e[1;31mServer is not reachable\e[0m"
       exit 1
       ;;
+    2) ### Config file is Missing
+      echo -e "\e[1;31mConfig file missing on Server!!"
+      exit 1
+      ;;
     100) ## Nginx service failed and not running
        systemctl restart nginx
        netstat -lntp | grep nginx
