ss

diff --git a/tools/roboshop-issue-tracker/functions b/tools/roboshop-issue-tracker/functions
--- a/tools/roboshop-issue-tracker/functions
+++ b/tools/roboshop-issue-tracker/functions
@@ -1,10 +1,28 @@
+R01() {
+  echo -e "-> Your Server $IP is not running, Ensure it is running"
+}
+R02() {
+  echo -e "-> Your Server might be running, But the Security Group has not opened the ports, Ensure you attach the security group with all the ports opened as demonstrated during the training"
+}
+EXIT() {
+  case $1 in
+    CON1)
+      # This is for SSH connection Failure , SSH port not reachable over nc
+      echo -e "SSH Connection to node is failure"
+      R1;R2
+      ;;
+  esac
+  exit 1
+}
 CHECK_CONNECTION() {
+  echo -e "Checking DNS Record"
+
   echo -e "Checking SSH Connection to $IP"
   nc -w 5 -z $IP 22 &>/dev/null
   if [ $? -eq 0 ]; then
-    echo -e "Connection \e[1;32mSUCCESS\e[0m"
+    echo -e "Connection SSH \e[1;32mSUCCESS\e[0m"
   else
-    echo -e "Connection \e[1;31mFAILURE\e[0m"
+    echo -e "Connection SSH \e[1;31mFAILURE\e[0m"
     EXIT CON1
   fi
 }
