ss

diff --git a/tools/roboshop-issue-tracker/functions b/tools/roboshop-issue-tracker/functions
--- a/tools/roboshop-issue-tracker/functions
+++ b/tools/roboshop-issue-tracker/functions
@@ -1,137 +1,11 @@
-LOG=/tmp/issue-track.log
-rm -f $LOG
-
-## Color Print
-## Color Code - XX
-# b-Black, R-RED, G-GREEN, Y-YELLOW, B-BLUE, M-MAGENTA, C-CYAN, w-white
-# B-BOLD, N-NORMAL
-
-wB() {
-  echo -e "\e[1m${1}\e[0m"
-}
-
-CB() {
-  echo -e "\e[1;36m${1}\e[0m"
-}
-
-RBPRINT() {
-  echo -e "\e[1;31m${1}\e[0m"
-}
-
-GBPRINT() {
-  echo -e "\e[1;32m${1}\e[0m"
-}
-
-NLPRINT() {
-  echo -e "\n"
-}
-
-BPRINT() {
-  echo -e "\e[1m${1}\e[0m"
-}
-
-PRINT() {
-  echo -e "${1}\e[0m"
-}
-
-DLIM() {
-  echo -e "---------------------------------------------------------------------------------------------------------"
-}
-
-DLIM_DOWN() {
-  echo -e "_________________________________________________________________________________________________________"
-}
-
-DLIM_UP() {
-  echo -e "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾"
-}
-
-EXIT() {
-  DLIM_UP
-  BPRINT "Following are the solutions you can try\n"
-  for i in "$@"; do
-    echo -e "\t\e[1;36m✓  -  ${i}\e[0m"
-  done
-  DLIM
-  exit 1
-}
-
-CONCLUDE() {
-  DLIM_UP
-  BPRINT "${1}"
-  DLIM_DOWN
-}
-
-STAT() {
-  if [ $? -eq 0 ]; then
-    wB "$1 - \e[32mSUCCESS"
-  else
-    wB "$1 - \e[31mFAILURE"
-    EXIT
-  fi
-}
-
-CHECK_CONNECTION() {
-  echo -e "Checking DNS Record"
-  host $IP &>>${LOG}
-  STAT "DNS Record Check"
-
-  echo "Checking SSH Connection to $IP"
-  nc -w 5 -z $IP 22 &>/dev/null
-  if [ $? -eq 0 ]; then
-    wB "Connection SSH \e[1;32mSUCCESS\e[0m"
-  else
-    wB "Connection SSH \e[1;31mFAILURE\e[0m"
-    EXIT CON1
-  fi
-
-  if [ -n "${DBPORT}" ]; then
-    nc -w 5 -z ${IP} ${DBPORT} &>/dev/null
-    if [ $? -eq 0 ]; then
-      wB "Port Check to MongoDB is \e[32mSUCCESS"
-    else
-      wB "Port Check to MongoDB is \e[31mFAILURE"
-      EXIT CON2
-    fi
-  fi
-}
-
-CHECK_SSH_CONNECTION() {
-  nc -w 5 -z $1 22 &>/dev/null
-  if [ $? -eq 0 ]; then
-    PRINT "SSH Connection to \e[1m ${1} - \e[32m SUCCESS"
-    return 0
-  else
-    BPRINT "SSH Connection to \e[1m ${1} - \e[31m FAILED"
-    return 1
-  fi
-}
-
-COMPONENT_HEAD() {
-  DLIM_UP
-  BPRINT " ++++++++++ $1 CHECKS ++++++++++"
-  DLIM_DOWN
-}
-
-SCENARIO_HEAD() {
-  DLIM_UP
-  BPRINT "\e[35mSCENARIO\e[0m - \e[1m $1"
-  DLIM_DOWN
-  NLPRINT
-}
-
-STAT_CONNECTION() {
-  nc -w 5 -z ${1} ${2} &>/dev/null
-  if [ $? -eq 0 ]; then
-    BPRINT "${3} Connection to ${1} on PORT ${2} - \e[32mSUCCESS\n"
-    return 0
-  else
-    BPRINT "${3} Connection to ${1} on PORT ${2} - \e[31mFAILURE\n"
-    return 1
-  fi
-}
-
-STAT_SERVICE() {
-  ssh ${1} "systemctl is-active --quiet ${2}" 2>/dev/null
-  return $?
+CASE() {
+  case $1 in
+    1) ## Nginx service failed and not running
+       systemctl restart nginx
+       netstat -lntp | grep nginx
+       if [ $? -ne 0 ]; then
+         systemctl status -l nginx
+      fi
+    ;;
+  esac
 }
