ss

diff --git a/tools/roboshop-issue-tracker/solutions b/tools/roboshop-issue-tracker/solutions
--- a/tools/roboshop-issue-tracker/solutions
+++ b/tools/roboshop-issue-tracker/solutions
@@ -38,6 +38,11 @@ SOLUTION() {
       echo -e "RabbitMQ Service is not running, Ensure you install rabbitmq and start rabbitmq-servie"
       exit 1
       ;;
+    1000) ### RabbitMQ Username or Password missing in payment service file
+      echo -e "RabbitMQ Username or Password missing in the payment service file"
+      echo -e "Try checking the username and password with ${TC}cat /etc/systemd/system/payment.service${N}"
+      echo -e "Ensure you have username in AMQP_USER parameter and Password in AMQP_PASS Parameter"
+      exit 1
    esac
 }
 
